In [15]:
import pandas as pd
import numpy as np
import random
df = pd.DataFrame(
          {"a" : [4, 5, 6], 
           "b" : [7, 8, 9], 
           "c" : [10, 11, 12]},    
        index = [1, 4, 3])

In [9]:
print(df)

   a  b   c
1  4  7  10
4  5  8  11
3  6  9  12

In [10]:
# converts columns into rows 

pd.melt(df)

  variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [11]:
df.reset_index()

   index  a  b   c
0      1  4  7  10
1      4  5  8  11
2      3  6  9  12

In [13]:
#select first n rows
df.head(2)

   a  b   c
1  4  7  10
4  5  8  11

In [14]:
#select last n rows

df.tail(1)

   a  b   c
3  6  9  12

In [39]:
df.index = ["r1", "r2", "r3"]

print(df)

    a  b   c
r1  4  7  10
r2  5  8  11
r3  6  9  12

In [18]:
x = pd.DataFrame(np.random.rand(233, 10))

print(x)

            0         1         2         3         4         5         6  \
0    0.718766  0.222445  0.926037  0.683779  0.974936  0.366011  0.947513
1    0.237981  0.306754  0.687207  0.709266  0.396040  0.124758  0.519110
2    0.043698  0.280513  0.845395  0.907767  0.925710  0.210147  0.726758
3    0.699423  0.005357  0.780659  0.208180  0.329310  0.381532  0.310456
4    0.900934  0.086850  0.661723  0.908354  0.942709  0.876154  0.324489
..        ...       ...       ...       ...       ...       ...       ...
228  0.537120  0.759819  0.184291  0.723661  0.061999  0.883482  0.247247
229  0.671128  0.324390  0.193569  0.337398  0.834946  0.274112  0.098577
230  0.895242  0.282639  0.460730  0.952605  0.631301  0.660332  0.180000
231  0.750130  0.893440  0.331331  0.961370  0.621105  0.767777  0.260527
232  0.675164  0.297541  0.142456  0.777072  0.895158  0.628179  0.513372

            7         8         9
0    0.593980  0.633653  0.755742
1    0.330082  0.389594  0.976317
2    0.169969  0.872887  0.547833
3    0.116012  0.288996  0.196740
4    0.940299  0.031561  0.401652
..        ...       ...       ...
228  0.471924  0.798178  0.456938
229  0.747191  0.131590  0.930182
230  0.080557  0.584865  0.863946
231  0.705831  0.223371  0.629096
232  0.948778  0.630433  0.872896

[233 rows x 10 columns]

In [ ]:
#gives the rows with smallest value in the soecified column, automatically sorts the rows 
# for eg give me 3 rows with smallest value in column 7
(x.nsmallest(3,[7]))

,0,1,2,3,4,5,6,7,8,9
87,0.228272,0.446656,0.219887,0.431618,0.749242,0.182134,0.677023,0.001976,0.237490,0.757667
105,0.425519,0.161318,0.689815,0.824484,0.282893,0.465033,0.080240,0.021247,0.179045,0.502448
144,0.853188,0.885694,0.777876,0.290102,0.477291,0.055554,0.363611,0.022549,0.205415,0.491215

In [27]:
print(x.columns)

RangeIndex(start=0, stop=10, step=1)

In [33]:
x.to_csv("random.csv")

In [35]:
x.describe()

,0,1,2,3,4,5,6,7,8,9
count,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000
mean,0.515499,0.533143,0.521710,0.482978,0.487031,0.455437,0.485460,0.477225,0.489835,0.498060
std,0.286661,0.285360,0.276250,0.283168,0.285029,0.271465,0.281168,0.287364,0.280522,0.293864
min,0.000721,0.000771,0.002012,0.001525,0.002283,0.001308,0.004074,0.001976,0.003344,0.005226
25%,0.277681,0.282710,0.291874,0.232494,0.263101,0.226900,0.244328,0.206255,0.256688,0.228227
50%,0.540817,0.528168,0.522695,0.481090,0.491587,0.425707,0.452871,0.471924,0.456645,0.499116
75%,0.750130,0.804252,0.777876,0.708796,0.718422,0.662147,0.726460,0.708579,0.732592,0.755742
max,0.999414,0.998575,0.989543,0.997425,0.993001,0.997008,0.992944,0.998808,0.994110,0.996781

In [37]:
hehe = pd.read_csv("random.csv")
print(hehe)

     Unnamed: 0         0         1         2         3         4         5  \
0             0  0.718766  0.222445  0.926037  0.683779  0.974936  0.366011
1             1  0.237981  0.306754  0.687207  0.709266  0.396040  0.124758
2             2  0.043698  0.280513  0.845395  0.907767  0.925710  0.210147
3             3  0.699423  0.005357  0.780659  0.208180  0.329310  0.381532
4             4  0.900934  0.086850  0.661723  0.908354  0.942709  0.876154
..          ...       ...       ...       ...       ...       ...       ...
228         228  0.537120  0.759819  0.184291  0.723661  0.061999  0.883482
229         229  0.671128  0.324390  0.193569  0.337398  0.834946  0.274112
230         230  0.895242  0.282639  0.460730  0.952605  0.631301  0.660332
231         231  0.750130  0.893440  0.331331  0.961370  0.621105  0.767777
232         232  0.675164  0.297541  0.142456  0.777072  0.895158  0.628179

            6         7         8         9
0    0.947513  0.593980  0.633653  0.755742
1    0.519110  0.330082  0.389594  0.976317
2    0.726758  0.169969  0.872887  0.547833
3    0.310456  0.116012  0.288996  0.196740
4    0.324489  0.940299  0.031561  0.401652
..        ...       ...       ...       ...
228  0.247247  0.471924  0.798178  0.456938
229  0.098577  0.747191  0.131590  0.930182
230  0.180000  0.080557  0.584865  0.863946
231  0.260527  0.705831  0.223371  0.629096
232  0.513372  0.948778  0.630433  0.872896

[233 rows x 11 columns]

In [ ]:
# dataframes are collection of series

In [41]:
ser = pd.Series(np.random.rand(5))

print(ser)

0    0.357476
1    0.718141
2    0.630437
3    0.530227
4    0.804339
dtype: float64

In [ ]:
#when we are chaining , we use loc  
#x[0][0] = 12345
x.loc[0,0] = 12345

x.head(3)

,0,1,2,3,4,5,6,7,8,9
0,12345.000000,0.222445,0.926037,0.683779,0.974936,0.366011,0.947513,0.593980,0.633653,0.755742
1,0.237981,0.306754,0.687207,0.709266,0.396040,0.124758,0.519110,0.330082,0.389594,0.976317
2,0.043698,0.280513,0.845395,0.907767,0.925710,0.210147,0.726758,0.169969,0.872887,0.547833

In [45]:
x.columns = list("ABCDEFGHIJ")

x.head(3)

,A,B,C,D,E,F,G,H,I,J
0,12345.000000,0.222445,0.926037,0.683779,0.974936,0.366011,0.947513,0.593980,0.633653,0.755742
1,0.237981,0.306754,0.687207,0.709266,0.396040,0.124758,0.519110,0.330082,0.389594,0.976317
2,0.043698,0.280513,0.845395,0.907767,0.925710,0.210147,0.726758,0.169969,0.872887,0.547833

In [52]:
x.loc[(x['A'] < 0.5) & (x['B'] > 0.5)]

,A,B,C,D,E,F,G,H,I,J
7,0.070718,0.528168,0.401762,0.708796,0.288581,0.249226,0.818498,0.366020,0.960793,0.942898
8,0.309691,0.530973,0.798155,0.676152,0.541479,0.091236,0.187043,0.290466,0.590482,0.762486
15,0.214052,0.506915,0.718110,0.690721,0.049349,0.975219,0.731071,0.042379,0.383907,0.659543
17,0.072017,0.793047,0.782722,0.776040,0.178830,0.217040,0.798475,0.460625,0.893752,0.137025
21,0.088161,0.726222,0.502570,0.892647,0.303446,0.579362,0.723089,0.621319,0.554824,0.583415
28,0.026733,0.983395,0.522695,0.753353,0.590994,0.515844,0.133754,0.186205,0.040410,0.981390
33,0.116923,0.556377,0.829595,0.223493,0.740536,0.764239,0.107105,0.085148,0.932297,0.741612
34,0.262416,0.760561,0.089612,0.229276,0.659157,0.894333,0.870050,0.573670,0.345362,0.590855
37,0.206186,0.542372,0.085476,0.694244,0.028405,0.213830,0.360237,0.188347,0.876542,0.367022
39,0.453732,0.591424,0.635259,0.068181,0.245253,0.261608,0.390098,0.291504,0.377242,0.917369
41,0.481662,0.600015,0.466977,0.541893,0.659238,0.477408,0.226673,0.370165,0.574893,0.086244
44,0.353181,0.769072,0.391250,0.338126,0.015238,0.123631,0.652415,0.817698,0.801026,0.469473
46,0.302564,0.857976,0.857843,0.354175,0.718422,0.906318,0.427871,0.819752,0.395367,0.470704
53,0.394835,0.955149,0.784222,0.979017,0.114728,0.965898,0.242321,0.202846,0.990584,0.363463
57,0.464640,0.917316,0.426768,0.172154,0.441737,0.261963,0.309560,0.921469,0.367979,0.569213
65,0.297415,0.934159,0.184995,0.270134,0.378887,0.277867,0.204601,0.221020,0.219662,0.119028
67,0.182234,0.795750,0.311323,0.471652,0.918918,0.446777,0.586490,0.461738,0.905318,0.114050
71,0.293526,0.500417,0.132940,0.511823,0.393976,0.336565,0.024032,0.443466,0.687728,0.373014
77,0.006886,0.646739,0.291874,0.512080,0.534303,0.950736,0.710641,0.634946,0.087535,0.005226
78,0.045634,0.555139,0.210290,0.890171,0.634717,0.137830,0.715635,0.611283,0.563461,0.641570
83,0.178201,0.891401,0.055368,0.164478,0.242741,0.324993,0.123573,0.541416,0.698595,0.325392
88,0.402909,0.812044,0.295398,0.344440,0.674929,0.522213,0.741732,0.915813,0.359766,0.405018
90,0.159584,0.612280,0.913342,0.993035,0.652537,0.872486,0.361256,0.884178,0.635968,0.279425
92,0.275124,0.908319,0.361059,0.884361,0.084319,0.991414,0.817994,0.296341,0.915515,0.630460
94,0.295255,0.573001,0.951733,0.941998,0.880858,0.578186,0.826754,0.735814,0.256688,0.228227
104,0.256174,0.944953,0.081539,0.052858,0.682469,0.239272,0.081178,0.589116,0.178160,0.962675
124,0.389485,0.777034,0.428129,0.429059,0.108463,0.737656,0.954142,0.980239,0.595804,0.878311
128,0.024530,0.892737,0.115536,0.701205,0.715976,0.015465,0.445738,0.968912,0.885059,0.316857
136,0.259382,0.574615,0.414826,0.052769,0.983913,0.262233,0.326802,0.401531,0.186002,0.711633
140,0.216506,0.820444,0.547996,0.588825,0.621257,0.567219,0.726460,0.850006,0.132992,0.475723
145,0.276393,0.740492,0.721609,0.540946,0.785676,0.947948,0.531675,0.289199,0.105204,0.703594
146,0.380642,0.747593,0.544087,0.561022,0.882001,0.780603,0.188320,0.756011,0.664197,0.025090
156,0.458654,0.894591,0.565888,0.568495,0.536024,0.163652,0.354308,0.555576,0.056100,0.357270
162,0.096423,0.894761,0.301315,0.178670,0.438646,0.358294,0.136101,0.511863,0.422767,0.058503
163,0.016599,0.502003,0.463550,0.377411,0.825680,0.185429,0.496850,0.532842,0.111340,0.175632
165,0.081367,0.710187,0.618893,0.889817,0.472688,0.887299,0.232105,0.829677,0.406864,0.857005
170,0.032476,0.840247,0.846450,0.232494,0.161843,0.408651,0.374122,0.734513,0.278159,0.269354
171,0.116879,0.811683,0.902828,0.013907,0.084219,0.645812,0.583941,0.838358,0.902447,0.580491
173,0.234429,0.843368,0.697175,0.010139,0.654869,0.201584,0.869514,0.206255,0.793437,0.965399
176,0.011238,0.861367,0.664714,0.278422,0.908244,0.093051,0.143698,0.043156,0.607731,0.132166
182,0.224027,0.764971,0.186613,0.385697,0.900037,0.151415,0.699909,0.560537,0.424750,0.325211
183,0.343442,0.951702,0.167562,0.715205,0.310052,0.977724,0.983245,0.054082,0.613175,0.331983
186,0.279084,0.741217,0.633311,0.304436,0.295644,0.864668,0.082337,0.438953,0.065300,0.961726
189,0.351788,0.537976,0.038552,0.001525,0.916474,0.858515,0.435663,0.557940,0.504544,0.426848
192,0.341282,0.781169,0.110719,0.709638,0.811405,0.598951,0.015120,0.371436,0.850912,0.686964
193,0.298391,0.622691,0.785578,0.644722,0.571371,0.672683,0.081680,0.563840,0.662802,0.858110
196,0.124696,0.742250,0.367546,0.637314,0.787304,0.323326,0.382873,0.121815,0.815857,0.569713
197,0.258747,0.954476,0.944340,0.619316,0.113906,0.396073,0.722852,0.068533,0.982686,0.966550
198,0.310745,0.547358,0.646685,0.726263,0.596405,0.815288,0.865196,0.235056,0.955391,0.978179
200,0.127298,0.887477,0.719789,0.463120,0.520084,0.279653,0.378350,0.846779,0.163970,0.929092
207,0.220087,0.638484,0.423273,0.666485,0.741591,0.600833,0.407986,0.820350,0.249233,0.007221
217,0.306649,0.875921,0.537546,0.421226,0.431746,0.012613,0.264152,0.098355,0.295083,0.148179
221,0.157629,0.604825,0.383248,0.413540,0.836731,0.384781,0.417991,0.171280,0.022777,0.933780
224,0.155420,0.929748,0.443665,0.601443,0.329414,0.666909,0.281005,0.386240,0.304748,0.159946

In [ ]:
 # use iloc if you want to select by position

x.iloc[0,0]

# used [0,0] in place of [0,A]

12345.0

In [55]:
x.iloc[[1,5],[2,5]]

          C         F
1  0.687207  0.124758
5  0.188911  0.247303

In [ ]:
# use inplace = True to make changes in the original dataframe instead of creating a new one

In [57]:
x.reset_index(drop = True, inplace = True)   # resets index and drops the old index column

In [58]:
x['A'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
228    False
229    False
230    False
231    False
232    False
Name: A, Length: 233, dtype: bool

In [ ]:
x.dropna(how = 'all') # drops rows where all values are null

# don forget that it creates a copy, orgiganl x is not changed

In [ ]:
x.drop_duplicates(subset = ['A'])   # drops the rows where column A has null values