In [2]:
import pandas as pd
import numpy as np
import random
df = pd.DataFrame(
          {"a" : [4, 5, 6], 
           "b" : [7, 8, 9], 
           "c" : [10, 11, 12]},    
        index = [1, 4, 3])

In [3]:
print(df)

   a  b   c
1  4  7  10
4  5  8  11
3  6  9  12

In [4]:
# converts columns into rows 

pd.melt(df)

  variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [5]:
df.reset_index()

   index  a  b   c
0      1  4  7  10
1      4  5  8  11
2      3  6  9  12

In [6]:
#select first n rows
df.head(2)

   a  b   c
1  4  7  10
4  5  8  11

In [7]:
#select last n rows

df.tail(1)

   a  b   c
3  6  9  12

In [8]:
df.index = ["r1", "r2", "r3"]

print(df)

    a  b   c
r1  4  7  10
r2  5  8  11
r3  6  9  12

In [9]:
x = pd.DataFrame(np.random.rand(233, 10))

print(x)

            0         1         2         3         4         5         6  \
0    0.766294  0.435558  0.283841  0.828098  0.040926  0.646360  0.160850
1    0.242638  0.816780  0.075306  0.986326  0.794634  0.727749  0.323177
2    0.632468  0.246131  0.000598  0.846768  0.315080  0.368923  0.692655
3    0.001362  0.648214  0.200873  0.834739  0.636913  0.379975  0.668940
4    0.449318  0.745140  0.756124  0.860459  0.191523  0.757239  0.773601
..        ...       ...       ...       ...       ...       ...       ...
228  0.552071  0.385082  0.105683  0.673579  0.490351  0.973062  0.545741
229  0.774753  0.204672  0.595179  0.140651  0.126586  0.631514  0.415223
230  0.712323  0.453787  0.853857  0.104693  0.410830  0.610200  0.808740
231  0.738369  0.498723  0.484452  0.675534  0.887935  0.081246  0.746730
232  0.141114  0.715767  0.660025  0.499658  0.020076  0.267658  0.637170

            7         8         9
0    0.611817  0.831040  0.238822
1    0.317992  0.272217  0.567238
2    0.844251  0.543303  0.273486
3    0.815744  0.551846  0.880257
4    0.547882  0.236692  0.100865
..        ...       ...       ...
228  0.613456  0.581319  0.876793
229  0.078091  0.931728  0.713623
230  0.998900  0.997255  0.412378
231  0.584436  0.963110  0.822520
232  0.674413  0.118809  0.545963

[233 rows x 10 columns]

In [10]:
#gives the rows with smallest value in the soecified column, automatically sorts the rows 
# for eg give me 3 rows with smallest value in column 7
(x.nsmallest(3,[7]))

,0,1,2,3,4,5,6,7,8,9
101,0.821462,0.278664,0.261955,0.015668,0.048248,0.182267,0.564821,0.003251,0.367752,0.366931
187,0.375746,0.212852,0.200873,0.461776,0.726559,0.198600,0.577559,0.004884,0.326059,0.380204
12,0.191897,0.923683,0.952034,0.766723,0.200676,0.068612,0.305203,0.016912,0.748827,0.383976

In [11]:
print(x.columns)

RangeIndex(start=0, stop=10, step=1)

In [12]:
x.to_csv("random.csv")

In [13]:
x.describe()

,0,1,2,3,4,5,6,7,8,9
count,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000
mean,0.497649,0.514488,0.492922,0.511824,0.483136,0.508577,0.515049,0.519834,0.500496,0.506665
std,0.269737,0.292549,0.290705,0.286195,0.285578,0.281039,0.289522,0.299981,0.289458,0.279543
min,0.001362,0.009512,0.000598,0.000439,0.020076,0.002285,0.001217,0.003251,0.001219,0.016279
25%,0.285006,0.256175,0.251480,0.267506,0.235280,0.284854,0.269710,0.260001,0.255451,0.259823
50%,0.482503,0.516073,0.468985,0.524263,0.485757,0.525235,0.505014,0.510255,0.508970,0.513974
75%,0.726521,0.780151,0.737127,0.764895,0.712319,0.739422,0.773601,0.789273,0.757647,0.727094
max,0.987834,0.999498,0.996586,0.992126,0.995856,0.994679,0.998956,0.998900,0.997255,0.995611

In [14]:
hehe = pd.read_csv("random.csv")
print(hehe)

     Unnamed: 0         0         1         2         3         4         5  \
0             0  0.766294  0.435558  0.283841  0.828098  0.040926  0.646360
1             1  0.242638  0.816780  0.075306  0.986326  0.794634  0.727749
2             2  0.632468  0.246131  0.000598  0.846768  0.315080  0.368923
3             3  0.001362  0.648214  0.200873  0.834739  0.636913  0.379975
4             4  0.449318  0.745140  0.756124  0.860459  0.191523  0.757239
..          ...       ...       ...       ...       ...       ...       ...
228         228  0.552071  0.385082  0.105683  0.673579  0.490351  0.973062
229         229  0.774753  0.204672  0.595179  0.140651  0.126586  0.631514
230         230  0.712323  0.453787  0.853857  0.104693  0.410830  0.610200
231         231  0.738369  0.498723  0.484452  0.675534  0.887935  0.081246
232         232  0.141114  0.715767  0.660025  0.499658  0.020076  0.267658

            6         7         8         9
0    0.160850  0.611817  0.831040  0.238822
1    0.323177  0.317992  0.272217  0.567238
2    0.692655  0.844251  0.543303  0.273486
3    0.668940  0.815744  0.551846  0.880257
4    0.773601  0.547882  0.236692  0.100865
..        ...       ...       ...       ...
228  0.545741  0.613456  0.581319  0.876793
229  0.415223  0.078091  0.931728  0.713623
230  0.808740  0.998900  0.997255  0.412378
231  0.746730  0.584436  0.963110  0.822520
232  0.637170  0.674413  0.118809  0.545963

[233 rows x 11 columns]

In [15]:
# dataframes are collection of series

In [16]:
ser = pd.Series(np.random.rand(5))

print(ser)

0    0.421829
1    0.061485
2    0.970624
3    0.633633
4    0.331320
dtype: float64

In [17]:
#when we are chaining , we use loc  
#x[0][0] = 12345
x.loc[0,0] = 12345

x.head(3)

,0,1,2,3,4,5,6,7,8,9
0,12345.000000,0.435558,0.283841,0.828098,0.040926,0.646360,0.160850,0.611817,0.831040,0.238822
1,0.242638,0.816780,0.075306,0.986326,0.794634,0.727749,0.323177,0.317992,0.272217,0.567238
2,0.632468,0.246131,0.000598,0.846768,0.315080,0.368923,0.692655,0.844251,0.543303,0.273486

In [18]:
x.columns = list("ABCDEFGHIJ")

x.head(3)

,A,B,C,D,E,F,G,H,I,J
0,12345.000000,0.435558,0.283841,0.828098,0.040926,0.646360,0.160850,0.611817,0.831040,0.238822
1,0.242638,0.816780,0.075306,0.986326,0.794634,0.727749,0.323177,0.317992,0.272217,0.567238
2,0.632468,0.246131,0.000598,0.846768,0.315080,0.368923,0.692655,0.844251,0.543303,0.273486

In [19]:
x.loc[(x['A'] < 0.5) & (x['B'] > 0.5)]

,A,B,C,D,E,F,G,H,I,J
1,0.242638,0.816780,0.075306,0.986326,0.794634,0.727749,0.323177,0.317992,0.272217,0.567238
3,0.001362,0.648214,0.200873,0.834739,0.636913,0.379975,0.668940,0.815744,0.551846,0.880257
4,0.449318,0.745140,0.756124,0.860459,0.191523,0.757239,0.773601,0.547882,0.236692,0.100865
5,0.177701,0.567224,0.400021,0.087922,0.374508,0.745597,0.495868,0.092933,0.848041,0.255884
12,0.191897,0.923683,0.952034,0.766723,0.200676,0.068612,0.305203,0.016912,0.748827,0.383976
13,0.110762,0.995140,0.016258,0.400148,0.338919,0.892545,0.278289,0.982898,0.644565,0.486394
14,0.143157,0.985945,0.659021,0.267506,0.995280,0.744626,0.102301,0.987585,0.541092,0.697806
26,0.486961,0.672436,0.830768,0.298545,0.257538,0.898203,0.645503,0.237739,0.152139,0.908440
28,0.278715,0.768504,0.713365,0.081743,0.075073,0.776019,0.901783,0.428083,0.456942,0.727094
33,0.188006,0.699006,0.681518,0.156845,0.921012,0.979313,0.478091,0.244780,0.730648,0.797937
38,0.400972,0.749782,0.548075,0.001821,0.376754,0.633247,0.024844,0.685416,0.760229,0.267406
40,0.305319,0.812812,0.193024,0.551383,0.244836,0.624301,0.457268,0.153684,0.404659,0.192320
48,0.305898,0.524772,0.492559,0.392012,0.758042,0.424171,0.900687,0.912296,0.737693,0.210182
50,0.470449,0.788175,0.005226,0.695648,0.982222,0.132363,0.001217,0.099294,0.804635,0.191667
51,0.383056,0.745367,0.390488,0.921882,0.619532,0.180342,0.427288,0.230811,0.095562,0.612803
53,0.403806,0.614652,0.842186,0.493448,0.620649,0.038396,0.442121,0.430972,0.104041,0.573569
59,0.296060,0.763603,0.141353,0.986280,0.250375,0.720129,0.073916,0.291472,0.403978,0.943061
60,0.461265,0.982191,0.315478,0.968397,0.441684,0.039638,0.276984,0.814768,0.145962,0.975990
64,0.469787,0.814530,0.913596,0.423602,0.134648,0.097479,0.834357,0.389720,0.431617,0.067035
78,0.043046,0.517011,0.395437,0.182299,0.438810,0.732712,0.462060,0.894445,0.950808,0.867690
82,0.312524,0.950742,0.099049,0.244477,0.905773,0.365891,0.153391,0.417114,0.907397,0.621502
83,0.348434,0.625472,0.947722,0.507710,0.411313,0.023397,0.334041,0.457836,0.935521,0.525560
87,0.234519,0.930877,0.878846,0.244353,0.172956,0.650769,0.521187,0.652260,0.231388,0.931185
88,0.460446,0.597558,0.335913,0.648646,0.379212,0.165758,0.295987,0.688095,0.922542,0.774263
89,0.061091,0.679641,0.333511,0.228607,0.520791,0.882524,0.992794,0.097081,0.769240,0.165162
94,0.399690,0.919902,0.048405,0.490710,0.305241,0.752228,0.515969,0.956318,0.060766,0.919043
95,0.247911,0.626366,0.962036,0.637636,0.125616,0.676681,0.060371,0.360685,0.090799,0.294542
96,0.258834,0.963761,0.949001,0.638870,0.541976,0.110154,0.007323,0.240877,0.831582,0.789983
98,0.001464,0.610211,0.738089,0.737176,0.946823,0.521789,0.061627,0.839082,0.483866,0.335949
99,0.454853,0.654419,0.952547,0.363352,0.920086,0.546041,0.830007,0.979982,0.296805,0.336719
100,0.233024,0.652727,0.335306,0.593128,0.079704,0.216462,0.773010,0.885445,0.704183,0.947696
102,0.170884,0.557484,0.494743,0.608551,0.231342,0.744932,0.630027,0.499635,0.576145,0.699506
119,0.240520,0.630176,0.585731,0.343976,0.122351,0.384129,0.990305,0.874401,0.083879,0.203893
121,0.336726,0.895800,0.787808,0.824513,0.104277,0.348218,0.565325,0.574118,0.704376,0.022766
124,0.484309,0.744076,0.104352,0.054181,0.616342,0.536091,0.673729,0.470852,0.537789,0.076477
137,0.465746,0.515485,0.143051,0.099742,0.352501,0.620413,0.421988,0.315103,0.020235,0.208797
142,0.191973,0.706541,0.138450,0.448482,0.238282,0.835208,0.465689,0.977937,0.036236,0.828540
146,0.382665,0.740798,0.439202,0.017778,0.844492,0.442173,0.477106,0.401722,0.588971,0.908411
150,0.293611,0.545061,0.864535,0.231327,0.908618,0.452389,0.702407,0.902857,0.428338,0.831666
152,0.443041,0.658827,0.168288,0.000439,0.337001,0.833045,0.581394,0.654075,0.063618,0.047990
153,0.134006,0.958226,0.497381,0.482175,0.678022,0.251825,0.762433,0.972777,0.320267,0.218458
164,0.405595,0.948488,0.196641,0.858859,0.417223,0.974498,0.388235,0.677852,0.369516,0.262782
166,0.354171,0.820294,0.662502,0.442574,0.875682,0.510207,0.026558,0.159044,0.146288,0.607468
168,0.038068,0.939421,0.729619,0.976475,0.089098,0.748256,0.330804,0.455996,0.921437,0.820388
176,0.314890,0.706443,0.243440,0.086088,0.570482,0.350863,0.875028,0.410537,0.029216,0.956191
178,0.215033,0.529348,0.185197,0.442433,0.083024,0.674425,0.920903,0.108081,0.330314,0.885134
195,0.296568,0.569784,0.192326,0.409180,0.394093,0.286425,0.177320,0.173830,0.710345,0.225515
197,0.482503,0.783827,0.911275,0.717166,0.905012,0.433230,0.265898,0.680478,0.884575,0.210780
201,0.190816,0.822367,0.385189,0.163753,0.113637,0.525235,0.887329,0.910878,0.881251,0.093316
207,0.010761,0.656781,0.916957,0.365043,0.637445,0.027619,0.478040,0.928112,0.317240,0.502603
209,0.273088,0.599623,0.404442,0.824373,0.411032,0.226156,0.363120,0.255523,0.057681,0.154681
213,0.255442,0.535815,0.706117,0.575776,0.533530,0.100945,0.659043,0.051670,0.532896,0.016279
214,0.483998,0.576666,0.209598,0.895137,0.278929,0.282165,0.245431,0.057619,0.931330,0.451535
217,0.362492,0.847085,0.787974,0.547456,0.949488,0.966018,0.303417,0.301566,0.795229,0.126470
220,0.075146,0.780844,0.430589,0.938793,0.434007,0.048584,0.887251,0.233267,0.290840,0.612073
221,0.037024,0.829643,0.752131,0.386135,0.775565,0.542858,0.873559,0.679097,0.377637,0.227057
222,0.209099,0.934613,0.963010,0.650676,0.868511,0.467924,0.229245,0.143876,0.196153,0.367222
225,0.113057,0.930190,0.607836,0.833717,0.082536,0.067921,0.316781,0.274835,0.530054,0.900582
232,0.141114,0.715767,0.660025,0.499658,0.020076,0.267658,0.637170,0.674413,0.118809,0.545963

In [20]:
 # use iloc if you want to select by position

x.iloc[0,0]

# used [0,0] in place of [0,A]

12345.0

In [21]:
x.iloc[[1,5],[2,5]]

          C         F
1  0.075306  0.727749
5  0.400021  0.745597

In [22]:
# use inplace = True to make changes in the original dataframe instead of creating a new one

In [23]:
x.reset_index(drop = True, inplace = True)   # resets index and drops the old index column

In [24]:
x['A'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
228    False
229    False
230    False
231    False
232    False
Name: A, Length: 233, dtype: bool

In [ ]:
x.dropna(how = 'all') # drops rows where all values are null

# don't forget that it creates a copy, original x is not changed

,A,B,C,D,E,F,G,H,I,J
0,12345.000000,0.435558,0.283841,0.828098,0.040926,0.646360,0.160850,0.611817,0.831040,0.238822
1,0.242638,0.816780,0.075306,0.986326,0.794634,0.727749,0.323177,0.317992,0.272217,0.567238
2,0.632468,0.246131,0.000598,0.846768,0.315080,0.368923,0.692655,0.844251,0.543303,0.273486
3,0.001362,0.648214,0.200873,0.834739,0.636913,0.379975,0.668940,0.815744,0.551846,0.880257
4,0.449318,0.745140,0.756124,0.860459,0.191523,0.757239,0.773601,0.547882,0.236692,0.100865
...,...,...,...,...,...,...,...,...,...,...
228,0.552071,0.385082,0.105683,0.673579,0.490351,0.973062,0.545741,0.613456,0.581319,0.876793
229,0.774753,0.204672,0.595179,0.140651,0.126586,0.631514,0.415223,0.078091,0.931728,0.713623
230,0.712323,0.453787,0.853857,0.104693,0.410830,0.610200,0.808740,0.998900,0.997255,0.412378
231,0.738369,0.498723,0.484452,0.675534,0.887935,0.081246,0.746730,0.584436,0.963110,0.822520
232,0.141114,0.715767,0.660025,0.499658,0.020076,0.267658,0.637170,0.674413,0.118809,0.545963

In [26]:
x.drop_duplicates(subset = ['A'])   # drops the rows where column A has null values

,A,B,C,D,E,F,G,H,I,J
0,12345.000000,0.435558,0.283841,0.828098,0.040926,0.646360,0.160850,0.611817,0.831040,0.238822
1,0.242638,0.816780,0.075306,0.986326,0.794634,0.727749,0.323177,0.317992,0.272217,0.567238
2,0.632468,0.246131,0.000598,0.846768,0.315080,0.368923,0.692655,0.844251,0.543303,0.273486
3,0.001362,0.648214,0.200873,0.834739,0.636913,0.379975,0.668940,0.815744,0.551846,0.880257
4,0.449318,0.745140,0.756124,0.860459,0.191523,0.757239,0.773601,0.547882,0.236692,0.100865
...,...,...,...,...,...,...,...,...,...,...
228,0.552071,0.385082,0.105683,0.673579,0.490351,0.973062,0.545741,0.613456,0.581319,0.876793
229,0.774753,0.204672,0.595179,0.140651,0.126586,0.631514,0.415223,0.078091,0.931728,0.713623
230,0.712323,0.453787,0.853857,0.104693,0.410830,0.610200,0.808740,0.998900,0.997255,0.412378
231,0.738369,0.498723,0.484452,0.675534,0.887935,0.081246,0.746730,0.584436,0.963110,0.822520
232,0.141114,0.715767,0.660025,0.499658,0.020076,0.267658,0.637170,0.674413,0.118809,0.545963

In [29]:
df.isna()

        a      b      c
r1  False  False  False
r2  False  False  False
r3  False  False  False

In [28]:
df.isna().sum()  # gives the count of null values in each column

a    0
b    0
c    0
dtype: int64

In [30]:
df.duplicated()

r1    False
r2    False
r3    False
dtype: bool

In [ ]:
df.loc[df.duplicated(subset=['a'])]


# only shows the rows which are duplicated in column a, if you want to see all the rows which are duplicated in any column, just use df.duplicated() without subset

Empty DataFrame
Columns: [a, b, c]
Index: []

In [ ]:
# df.query('') does the same thing as df.loc[] but it is more readable and easier to use, especially when you have multiple conditions. It allows you to write your conditions in a more natural way, similar to how you would write them in SQL. For example, instead of writing df.loc[(df['A'] < 0.5) & (df['B'] > 0.5)], you can write df.query('A < 0.5 and B > 0.5'). This can make your code cleaner and easier to understand.